# Generated by Django 4.1 on 2022-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userinfo_username_alter_userinfo_pwd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vdinfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vd', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
