# Generated by Django 4.1 on 2022-09-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vdinfor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vdinfor',
        ),
    ]
