# Generated by Django 4.1 on 2022-10-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_pwd_userinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userid',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False),
        ),
    ]
