# Generated by Django 4.1 on 2022-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_sendfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msboardname', models.CharField(default='', max_length=50)),
                ('msboardcontent', models.CharField(default='', max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
