# Generated by Django 4.1 on 2022-11-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_messageboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
