# Generated by Django 4.1 on 2022-11-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
