# Generated by Django 4.1 on 2022-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newssubject',
            field=models.CharField(default='', max_length=250),
        ),
    ]
