# Generated by Django 4.1 on 2022-11-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_news_newssubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsurl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
