# Generated by Django 4.1.3 on 2022-11-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_news_newsurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploadAccount',
            field=models.CharField(default='', max_length=200),
        ),
    ]
