# Generated by Django 4.1.3 on 2022-11-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_document_uploadaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadAccount',
            field=models.CharField(default='', max_length=40),
        ),
    ]
