# Generated by Django 4.1.3 on 2022-11-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_document_uploadaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploadAccount',
        ),
    ]
